DROP TABLE IF EXISTS images;

CREATE TABLE images (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL ,
  mime_type VARCHAR(100) NOT NULL,
  public_id VARCHAR(255) NOT NULL UNIQUE,
  url_thumbnail VARCHAR(500) NOT NULL,
  url_medium VARCHAR(500) NOT NULL,
  url_large VARCHAR(500) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);